# dockerfile.fastapi
FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias necesarias
RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    python-multipart \
    pymongo \
    pillow \
    reportlab \
    python-dotenv \
    requests

# Copiar el código
COPY main.py .

# Puerto que usará Railway
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]